version: '3'
services:
  device24:
    build: .
    volumes:
      - "./device:/usr/src/app"
    environment:
      - LOCATION=umu/fac_info/lab24
  device23:
    build: .
    volumes:
      - "./device:/usr/src/app"
    environment:
      - LOCATION=umu/fac_info/lab23
  device04:
    build: .
    volumes:
      - "./device:/usr/src/app"
    environment:
      - LOCATION=umu/aulario_norte/a04
  mqtt-brocker:
    image: eclipse-mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
  kfk-producer:
    build: .
    volumes:
      - "./kfk-producer:/usr/src/app"
  kfk-consumer:
    build: .
    volumes:
      - "./kfk-consumer:/usr/src/app"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  influxdb:
    image: influxdb
    ports:
     - "8083:8083"
     - "8086:8086"
    environment:
     - INFLUXDB_DB=iotdata
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
