{
 "title": "UMU Temperatura",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Temperatura Actual",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "temperature",
     "query": "SELECT moving_average(\"value\", 10) FROM \"temperature\" GROUP BY \"location\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Histórico Temperatura",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "temperature",
     "query": "SELECT moving_average(\"value\", 10) FROM \"temperature\" WHERE $timeFilter GROUP BY \"location\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura Media en UMU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}